name: convert_extensions
description: Common convert methods exposed as static extensions method from the Dart core library and the convert package. Base64, ASCII, UTF8, Latin1, JSON, and more.
version: 0.1.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.15.1 <3.0.0'
dependencies:
  convert: ^3.0.1

dev_dependencies:
  lints: ^1.0.1
  test: ^1.21.0
